---
abstract: 'Apache Kafka low-level synchronous API, which does not use Zookeeper.'
author:
  - 'TrackingSoft LLC <sgladkov@trackingsoft.com>'
build_requires:
  Test::Deep: 0.109
  Test::Exception: 0.31
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kafka
no_index:
  directory:
    - t
    - inc
requires:
  Digest::CRC: 0.18
  Params::Util: 1.04
  perl: 5.010
version: 0.20
